import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/*Header*/}

    <header className="flex w-full p-5 justify-between">

      {/*Left*/}
      <div className='flex space-x-4 items-center'>
          <p>About</p>
          <p>Store</p>
      </div>

      {/*Right*/}
      <div className='flex space-x-4 items-center'>
        <p>Gmail</p>
        <p>Images</p>
      </div>
    </header>


    {/*Body*/}

    {/*Footer*/}
      
    </div>
  )
}
