import Head from 'next/head'
import Avatar from '../Components/avatar';
import {MicrophoneIcon, ViewGridIcon} from '@heroicons/react/solid';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/*Header*/}

    <header className="flex w-full p-5 justify-between text-md text-gray-700">

      {/*Left*/}
      <div className='flex space-x-4 items-center'>
          <p className="link">About</p>
          <p className="link">Store</p>
      </div>

      {/*Right*/}
      <div className='flex space-x-4 items-center'>
        <p className="link">Gmail</p>
        <p className="link">Images</p>

        <ViewGridIcon className="h-10 w-10 p-2"/>

        <Avatar url="https://github.com/chandran-jr.png" />
      </div>
    </header>


    {/*Body*/}

    {/*Footer*/}
      
    </div>
  )
}
